/* 自动生成：真实贵州实拍照片资产库（来源 Wikimedia Commons，含授权元数据）
   执行文档 §27 PhotoAsset 结构；verifiedRealPhoto=true 且 aiGenerated=false 才进入内容池 */
(function () {
  "use strict";
  const PHOTOS = [
  {
    "id": "gz_001",
    "title": "Fanjingshan, Guizhou, China",
    "category": "scenic",
    "city": "铜仁",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Fanjingshan-new.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Fanjingshan-new.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Fanjingshan-new.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AFanjingshan-new.jpg",
    "author": "sizzhot0",
    "license": "CC0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_002",
    "title": "Stone steps on Mount Fanjing, in Jiangkou County, Guizhou, C",
    "category": "scenic",
    "city": "铜仁",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20steps%2C%20Mount%20Fanjing%2C%20Picture7.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20steps%2C%20Mount%20Fanjing%2C%20Picture7.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20steps%2C%20Mount%20Fanjing%2C%20Picture7.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AStone_steps%2C_Mount_Fanjing%2C_Picture7.jpg",
    "author": "Huangdan2060",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_003",
    "title": "Jinding or Golden Summit of Mount Fanjing, in Jiangkou Count",
    "category": "scenic",
    "city": "铜仁",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020b.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020b.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020b.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AJinding%2C_Mount_Fanjing%2C_31_March_2020b.jpg",
    "author": "Huangdan2060",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_004",
    "title": "Jinding or Golden Summit of Mount Fanjing, in Jiangkou Count",
    "category": "scenic",
    "city": "铜仁",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020a.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020a.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020a.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AJinding%2C_Mount_Fanjing%2C_31_March_2020a.jpg",
    "author": "Huangdan2060",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_005",
    "title": "Xijiang Miao Village, Guizhou, China Evening",
    "category": "scenic",
    "city": "雷山",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Xijiang%20Guizhou%20Evening.jpeg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Xijiang%20Guizhou%20Evening.jpeg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Xijiang%20Guizhou%20Evening.jpeg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AXijiang_Guizhou_Evening.jpeg",
    "author": "MDRX",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_006",
    "title": "Thousand-households Miao（Hmub） village in Leishan，Guizhou.",
    "category": "scenic",
    "city": "雷山",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%A5%BF%E6%B1%9F%E5%8D%83%E6%88%B7%E8%8B%97%E5%AF%A8%EF%BC%88China%EF%BC%89.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%A5%BF%E6%B1%9F%E5%8D%83%E6%88%B7%E8%8B%97%E5%AF%A8%EF%BC%88China%EF%BC%89.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%A5%BF%E6%B1%9F%E5%8D%83%E6%88%B7%E8%8B%97%E5%AF%A8%EF%BC%88China%EF%BC%89.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E8%A5%BF%E6%B1%9F%E5%8D%83%E6%88%B7%E8%8B%97%E5%AF%A8%EF%BC%88China%EF%BC%89.jpg",
    "author": "sung ming whang",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_007",
    "title": "Maison en ossature bois des Miao, dans le Village miao des m",
    "category": "scenic",
    "city": "雷山",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao.ossature.bois.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao.ossature.bois.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao.ossature.bois.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMiao.ossature.bois.jpg",
    "author": "Popolon",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_008",
    "title": "Maison de bois Miao dans le Village miao des mille foyers de",
    "category": "scenic",
    "city": "雷山",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao.woodhouse.shop.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao.woodhouse.shop.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao.woodhouse.shop.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMiao.woodhouse.shop.jpg",
    "author": "Popolon",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_009",
    "title": "zhaoxing dong village guizhou china 2015",
    "category": "scenic",
    "city": "黎平",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/1%20zhaoxing%202015.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/1%20zhaoxing%202015.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/1%20zhaoxing%202015.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A1_zhaoxing_2015.jpg",
    "author": "Chensiyuan",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_010",
    "title": "Place: Zhaoxing, Liping County, Qiandongnan Miao and Dong Au",
    "category": "scenic",
    "city": "黎平",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20001.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20001.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20001.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AZhaoxing_001.jpg",
    "author": "Rutger van der Maar",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_011",
    "title": "Place: Zhaoxing, Liping County, Qiandongnan Miao and Dong Au",
    "category": "scenic",
    "city": "黎平",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20006.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20006.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20006.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AZhaoxing_006.jpg",
    "author": "Rutger van der Maar",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_012",
    "title": "Place: Zhaoxing, Liping County, Qiandongnan Miao and Dong Au",
    "category": "scenic",
    "city": "黎平",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20at%20night.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20at%20night.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaoxing%20at%20night.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AZhaoxing_at_night.jpg",
    "author": "Rutger van der Maar",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_013",
    "title": "Ground Opera Troupe at Qingyan Ancient Town, Guiyang. Taken ",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Ground%20Opera%20Troupe%20at%20Qingyan%20Ancient%20Town%2C%20Guiyang.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Ground%20Opera%20Troupe%20at%20Qingyan%20Ancient%20Town%2C%20Guiyang.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Ground%20Opera%20Troupe%20at%20Qingyan%20Ancient%20Town%2C%20Guiyang.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AGround_Opera_Troupe_at_Qingyan_Ancient_Town%2C_Guiyang.jpg",
    "author": "xiquinhosilva",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_014",
    "title": "Ground Opera Troupe performing at Qingyan Ancient Town, Guiy",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Ground%20Opera%20Troupe%20at%20Qingyan%20Ancient%20Town%2C%20Guiyang(2).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Ground%20Opera%20Troupe%20at%20Qingyan%20Ancient%20Town%2C%20Guiyang(2).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Ground%20Opera%20Troupe%20at%20Qingyan%20Ancient%20Town%2C%20Guiyang(2).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AGround_Opera_Troupe_at_Qingyan_Ancient_Town%2C_Guiyang(2).jpg",
    "author": "xiquinhosilva",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_015",
    "title": "Qingyan Ancient Town in Guiyang. Taken on 9 June 2018.",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Qingyan%20Ancient%20Town%2C%20Guiyang.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Qingyan%20Ancient%20Town%2C%20Guiyang.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Qingyan%20Ancient%20Town%2C%20Guiyang.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AQingyan_Ancient_Town%2C_Guiyang.jpg",
    "author": "xiquinhosilva",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_016",
    "title": "Qingyan Ancient Town, one of the most famous historical and ",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Qingyan%20Ancient%20Town%2086172-Guiyang%20(49047238217).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Qingyan%20Ancient%20Town%2086172-Guiyang%20(49047238217).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Qingyan%20Ancient%20Town%2086172-Guiyang%20(49047238217).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AQingyan_Ancient_Town_86172-Guiyang_(49047238217).jpg",
    "author": "xiquinhosilva",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_017",
    "title": "款識：頤齋仁弟法家屬。乙酉冬逖先張祖翼。",
    "category": "scenic",
    "city": "兴义",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%201ac47ce89e.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%201ac47ce89e.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%201ac47ce89e.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AZhang_Zuyi_-_1ac47ce89e.jpg",
    "author": "Zhang Zuyi",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_018",
    "title": "Zhang Zuyi (1849-1917) Calligraphy Couplet in Clerical Style",
    "category": "scenic",
    "city": "兴义",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%2068b48d3b77.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%2068b48d3b77.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%2068b48d3b77.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AZhang_Zuyi_-_68b48d3b77.jpg",
    "author": "Zhang Zuyi",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_019",
    "title": "Property From a Private North American Collection, Lot 2514-",
    "category": "scenic",
    "city": "兴义",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%202074cadb45.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%202074cadb45.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%202074cadb45.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AZhang_Zuyi_-_2074cadb45.jpg",
    "author": "Zhang Zuyi",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_020",
    "title": "Zhang Zuyi (1849-1917) Transcription of Wang Xizhi's Lanting",
    "category": "scenic",
    "city": "兴义",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%2061a4e22a34.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%2061a4e22a34.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Zhang%20Zuyi%20-%2061a4e22a34.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AZhang_Zuyi_-_61a4e22a34.jpg",
    "author": "Zhang Zuyi",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_021",
    "title": "Xiaoqikong, a World Heritage Sites in Guizhou, China.",
    "category": "scenic",
    "city": "荔波",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Xiaoqikong.JPG?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Xiaoqikong.JPG?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Xiaoqikong.JPG?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AXiaoqikong.JPG",
    "author": "Fanghong",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_022",
    "title": "Xiaoqikong, a World Heritage Sites in Guizhou, China.",
    "category": "scenic",
    "city": "荔波",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Libo%20Xian%20Banner%20Xiaoqikong.JPG?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Libo%20Xian%20Banner%20Xiaoqikong.JPG?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Libo%20Xian%20Banner%20Xiaoqikong.JPG?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ALibo_Xian_Banner_Xiaoqikong.JPG",
    "author": "Fanghong",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_023",
    "title": "Miao embroidery. Exhibit in the Yunnan Provincial Museum, Ku",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20embroidery%20-%20Yunnan%20Provincial%20Museum-%20DSC02190.JPG?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20embroidery%20-%20Yunnan%20Provincial%20Museum-%20DSC02190.JPG?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20embroidery%20-%20Yunnan%20Provincial%20Museum-%20DSC02190.JPG?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMiao_embroidery_-_Yunnan_Provincial_Museum-_DSC02190.JPG",
    "author": "Daderot",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_024",
    "title": "Child's festival skirt from Guizhou, China, Huangping, Miao ",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Child's%20festival%20skirt%2C%20Miao%20people%2C%20Honolulu%20Museum%20of%20Art%2011138.1.JPG?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Child's%20festival%20skirt%2C%20Miao%20people%2C%20Honolulu%20Museum%20of%20Art%2011138.1.JPG?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Child's%20festival%20skirt%2C%20Miao%20people%2C%20Honolulu%20Museum%20of%20Art%2011138.1.JPG?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AChild's_festival_skirt%2C_Miao_people%2C_Honolulu_Museum_of_Art_11138.1.JPG",
    "author": "Hiart",
    "license": "CC0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_025",
    "title": "Danjiang, Miao village, women at festival\nThe Miao is an eth",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Danjiang%2C%20Miao%20village%2C%20women%20at%20festival%20(40917045964).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Danjiang%2C%20Miao%20village%2C%20women%20at%20festival%20(40917045964).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Danjiang%2C%20Miao%20village%2C%20women%20at%20festival%20(40917045964).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADanjiang%2C_Miao_village%2C_women_at_festival_(40917045964).jpg",
    "author": "Arian Zwegers from Brussels, Belgium",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_026",
    "title": "Bac Ha market\nBắc Hà is a township and capital of Bắc Hà Dis",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/2007-12-09%20Bac%20Ha%20market%2C%20Flower%20Hmong%20girl.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/2007-12-09%20Bac%20Ha%20market%2C%20Flower%20Hmong%20girl.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/2007-12-09%20Bac%20Ha%20market%2C%20Flower%20Hmong%20girl.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A2007-12-09_Bac_Ha_market%2C_Flower_Hmong_girl.jpg",
    "author": "Arian Zwegers",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_027",
    "title": "chine guizou suoga, jeune fille miao à cornes fabricant un t",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Chine%20Miao%20%C3%A0%20corne%20603.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Chine%20Miao%20%C3%A0%20corne%20603.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Chine%20Miao%20%C3%A0%20corne%20603.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AChine_Miao_%C3%A0_corne_603.jpg",
    "author": "Yves Picq http://veton.picq.fr",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_028",
    "title": "Miao batik baby-carrying quilt. Fabric exhibited in the Yunn",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Fabric%20-%20Yunnan%20Nationalities%20Museum%20-%20DSC04148%20(cropped).JPG?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Fabric%20-%20Yunnan%20Nationalities%20Museum%20-%20DSC04148%20(cropped).JPG?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Fabric%20-%20Yunnan%20Nationalities%20Museum%20-%20DSC04148%20(cropped).JPG?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AFabric_-_Yunnan_Nationalities_Museum_-_DSC04148_(cropped).JPG",
    "author": "Daderot",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_029",
    "title": "Miao batik 苗族蜡染, Guizhou, 2016",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20batik%20%E8%8B%97%E6%97%8F%E8%9C%A1%E6%9F%93%2C%20Guizhou%2C%202016%20(52411662580).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20batik%20%E8%8B%97%E6%97%8F%E8%9C%A1%E6%9F%93%2C%20Guizhou%2C%202016%20(52411662580).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20batik%20%E8%8B%97%E6%97%8F%E8%9C%A1%E6%9F%93%2C%20Guizhou%2C%202016%20(52411662580).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMiao_batik_%E8%8B%97%E6%97%8F%E8%9C%A1%E6%9F%93%2C_Guizhou%2C_2016_(52411662580).jpg",
    "author": "JL Cogburn",
    "license": "CC BY-SA 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_030",
    "title": "Bijou de l'ethnie Miao (Hmong).",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Bijou%20Miao.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Bijou%20Miao.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Bijou%20Miao.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABijou_Miao.jpg",
    "author": "Vassil",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_031",
    "title": "Miao silver ornament. Jewelry in the Yunnan Nationalities Mu",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jewelry%20-%20Yunnan%20Nationalities%20Museum%20-%20DSC04107.JPG?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jewelry%20-%20Yunnan%20Nationalities%20Museum%20-%20DSC04107.JPG?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jewelry%20-%20Yunnan%20Nationalities%20Museum%20-%20DSC04107.JPG?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AJewelry_-_Yunnan_Nationalities_Museum_-_DSC04107.JPG",
    "author": "Daderot",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_032",
    "title": "錦繍中華民俗村",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20in%20China%20Folk%20Culture%20Village.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20in%20China%20Folk%20Culture%20Village.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20in%20China%20Folk%20Culture%20Village.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADong_Drum_Tower_in_China_Folk_Culture_Village.jpg",
    "author": "そらみみ",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_033",
    "title": "錦繍中華民俗村",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20in%20China%20Folk%20Culture%20Village%202.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20in%20China%20Folk%20Culture%20Village%202.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20in%20China%20Folk%20Culture%20Village%202.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADong_Drum_Tower_in_China_Folk_Culture_Village_2.jpg",
    "author": "そらみみ",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_034",
    "title": "錦繍中華民俗村",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20and%20Fengyuqiao%20Bridge%20in%20China%20Folk%20Culture%20Village.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20and%20Fengyuqiao%20Bridge%20in%20China%20Folk%20Culture%20Village.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Drum%20Tower%20and%20Fengyuqiao%20Bridge%20in%20China%20Folk%20Culture%20Village.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADong_Drum_Tower_and_Fengyuqiao_Bridge_in_China_Folk_Culture_Village.jpg",
    "author": "そらみみ",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_035",
    "title": "Take this dish for example. This is the most ordered dish at",
    "category": "food",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Inflation%20(4168156477).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Inflation%20(4168156477).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Inflation%20(4168156477).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AInflation_(4168156477).jpg",
    "author": "bfishadow from Beijing, China",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_036",
    "title": "Guiyang, Guizhou",
    "category": "food",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E4%B8%9D%E5%A8%83%E5%A8%83%20(28664736712).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E4%B8%9D%E5%A8%83%E5%A8%83%20(28664736712).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E4%B8%9D%E5%A8%83%E5%A8%83%20(28664736712).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E4%B8%9D%E5%A8%83%E5%A8%83_(28664736712).jpg",
    "author": "Caitriana Nicholson from 北京 ~ Beijing, 中国 ~ China",
    "license": "CC BY-SA 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_037",
    "title": "​遵义豆花面",
    "category": "food",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%B1%86%E8%8A%B1%E9%9D%A2%206993.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%B1%86%E8%8A%B1%E9%9D%A2%206993.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%B1%86%E8%8A%B1%E9%9D%A2%206993.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E8%B1%86%E8%8A%B1%E9%9D%A2_6993.jpg",
    "author": "Augusthaiho",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_038",
    "title": "this is a homemade Chongqing hot pot, with ingredients such ",
    "category": "food",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Homemade%20Hotpot.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Homemade%20Hotpot.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Homemade%20Hotpot.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHomemade_Hotpot.jpg",
    "author": "Jonathan Lin from Singapore, xinjiapore",
    "license": "CC BY-SA 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_039",
    "title": "​中国高速G6001贵阳东北绕城 北段 北向",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20NE%20Guiyang%20North.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20NE%20Guiyang%20North.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20NE%20Guiyang%20North.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AG6001_NE_Guiyang_North.jpg",
    "author": "Wahsaw",
    "license": "CC0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_040",
    "title": "​中国高速G6001东北绕城 东段 南向",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20NE%20Guiyang%20East%20Southbound.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20NE%20Guiyang%20East%20Southbound.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20NE%20Guiyang%20East%20Southbound.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AG6001_NE_Guiyang_East_Southbound.jpg",
    "author": "Wahsaw",
    "license": "CC0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_041",
    "title": "​中国高速G6001正线 龙洞堡段",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20Main%20line%20in%20Longdongbao%2C%20Guiyang%2C%20Guizhou.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20Main%20line%20in%20Longdongbao%2C%20Guiyang%2C%20Guizhou.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/G6001%20Main%20line%20in%20Longdongbao%2C%20Guiyang%2C%20Guizhou.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AG6001_Main_line_in_Longdongbao%2C_Guiyang%2C_Guizhou.jpg",
    "author": "Wahsaw",
    "license": "CC0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_042",
    "title": "Guiyang Skyline",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Guiyang%20Skyline.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Guiyang%20Skyline.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Guiyang%20Skyline.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AGuiyang_Skyline.jpg",
    "author": "Ryedamien",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_043",
    "title": "Rosa roxburghii in the botanical garden in Copenhagen",
    "category": "food",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa%20roxburghii%20(hips).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa%20roxburghii%20(hips).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa%20roxburghii%20(hips).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ARosa_roxburghii_(hips).jpg",
    "author": "user:Salvor",
    "license": "Public domain",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_044",
    "title": "Rosa hirtula, Koishikawa Botanical Gardens,  The University ",
    "category": "food",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa%20hirtula%2010.JPG?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa%20hirtula%2010.JPG?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa%20hirtula%2010.JPG?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ARosa_hirtula_10.JPG",
    "author": "Qwert1234",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_045",
    "title": "Young Miao woman in Yangshuo, China, wearing national costum",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20woman%20in%20Yangshuo%20(China).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20woman%20in%20Yangshuo%20(China).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Miao%20woman%20in%20Yangshuo%20(China).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMiao_woman_in_Yangshuo_(China).jpg",
    "author": "Thomas Schoch – www.retas.de",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_046",
    "title": "​三立台灣台綜藝節目《超級夜總會》於基隆市七堵區堵南國民小學操場錄影，第一段錄影在進行歌中劇前暫停錄影，苗可麗（右二）、",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Cheng%20Chung-yin%2C%20Lotus%20Wang%2C%20and%20Miao%20Ke-Li%20put%20on%20costumes%20at%20Super%20Night%20Club%2020160715.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Cheng%20Chung-yin%2C%20Lotus%20Wang%2C%20and%20Miao%20Ke-Li%20put%20on%20costumes%20at%20Super%20Night%20Club%2020160715.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Cheng%20Chung-yin%2C%20Lotus%20Wang%2C%20and%20Miao%20Ke-Li%20put%20on%20costumes%20at%20Super%20Night%20Club%2020160715.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACheng_Chung-yin%2C_Lotus_Wang%2C_and_Miao_Ke-Li_put_on_costumes_at_Super_Night_Club_20160715.jpg",
    "author": "Solomon203",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_047",
    "title": "Sheer joy and ecstasy writ large on the faces of these Chine",
    "category": "heritage",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Thrilled%20that%20their%20selfies%20came%20out%20well!%20(35946971000).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Thrilled%20that%20their%20selfies%20came%20out%20well!%20(35946971000).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Thrilled%20that%20their%20selfies%20came%20out%20well!%20(35946971000).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AThrilled_that_their_selfies_came_out_well!_(35946971000).jpg",
    "author": "shankar s. from Dubai, united arab emirates",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_048",
    "title": "​贵州省平塘县布依族村寨，当地村民演示梭织技术",
    "category": "city",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%B4%B5%E5%B7%9E%E6%A2%AD%E7%BB%87.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%B4%B5%E5%B7%9E%E6%A2%AD%E7%BB%87.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/%E8%B4%B5%E5%B7%9E%E6%A2%AD%E7%BB%87.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E8%B4%B5%E5%B7%9E%E6%A2%AD%E7%BB%87.jpg",
    "author": "Lkjidm",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_049",
    "title": "These are my personal notes taken during a geology presentat",
    "category": "scenic",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Diamonds%20-%20Their%20Geology%2C%20Geography%2C%20and%20History%20(20400181274).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Diamonds%20-%20Their%20Geology%2C%20Geography%2C%20and%20History%20(20400181274).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Diamonds%20-%20Their%20Geology%2C%20Geography%2C%20and%20History%20(20400181274).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADiamonds_-_Their_Geology%2C_Geography%2C_and_History_(20400181274).jpg",
    "author": "James St. John",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_050",
    "title": "Place: Sanjiang Dong Autonomous County, Liuzhou, Guangxi Zhu",
    "category": "scenic",
    "city": null,
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Chengyang%20tea%20field.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Chengyang%20tea%20field.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Chengyang%20tea%20field.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AChengyang_tea_field.jpg",
    "author": "Rutger van der Maar",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_051",
    "title": "The Malinghe River Bridge in Guizhou province, China",
    "category": "scenic",
    "city": "兴义",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge-2.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge-2.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge-2.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMalinghe_River_Bridge-2.jpg",
    "author": "Glabb",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_052",
    "title": "The Malinghe River Bridge in Guizhou province, China",
    "category": "scenic",
    "city": "兴义",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge-3.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge-3.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge-3.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMalinghe_River_Bridge-3.jpg",
    "author": "Glabb",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_053",
    "title": "The Malinghe River Bridge in Guizhou province, China",
    "category": "scenic",
    "city": "兴义",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Malinghe%20River%20Bridge.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMalinghe_River_Bridge.jpg",
    "author": "Glabb",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_054",
    "title": "bapa dong village guizhou 2015 panorama",
    "category": "scenic",
    "city": "从江",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/1%20bapa%20dong%20village%202015.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/1%20bapa%20dong%20village%202015.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/1%20bapa%20dong%20village%202015.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A1_bapa_dong_village_2015.jpg",
    "author": "Chensiyuan",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_055",
    "title": "Congjiang, Qiandongnan, Guizhou, China",
    "category": "scenic",
    "city": "从江",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Congjiang%2C%20Qiandongnan%2C%20Guizhou%2C%20China%20-%20panoramio%20(1).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Congjiang%2C%20Qiandongnan%2C%20Guizhou%2C%20China%20-%20panoramio%20(1).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Congjiang%2C%20Qiandongnan%2C%20Guizhou%2C%20China%20-%20panoramio%20(1).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACongjiang%2C_Qiandongnan%2C_Guizhou%2C_China_-_panoramio_(1).jpg",
    "author": "qdn_RZH",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_056",
    "title": "Congjiang, Qiandongnan, Guizhou, China",
    "category": "scenic",
    "city": "从江",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Congjiang%2C%20Qiandongnan%2C%20Guizhou%2C%20China%20-%20panoramio%20(2).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Congjiang%2C%20Qiandongnan%2C%20Guizhou%2C%20China%20-%20panoramio%20(2).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Congjiang%2C%20Qiandongnan%2C%20Guizhou%2C%20China%20-%20panoramio%20(2).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACongjiang%2C_Qiandongnan%2C_Guizhou%2C_China_-_panoramio_(2).jpg",
    "author": "qdn_RZH",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_057",
    "title": "中国贵州黄果树瀑布",
    "category": "scenic",
    "city": "安顺",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/HuangguoshuFall.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/HuangguoshuFall.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/HuangguoshuFall.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHuangguoshuFall.jpg",
    "author": "WaitinZ",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_058",
    "title": "Guizhou, waterfall, Huangguoshu waterfall",
    "category": "scenic",
    "city": "安顺",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%20Guizhou%20Province.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%20Guizhou%20Province.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%20Guizhou%20Province.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHuangguoshu_Waterfall_Guizhou_Province.jpg",
    "author": "Whoisgalt",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_059",
    "title": "Huangguoshu Waterfall Guizhou province",
    "category": "scenic",
    "city": "安顺",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%202.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%202.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%202.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHuangguoshu_Waterfall_2.jpg",
    "author": "Dounai",
    "license": "CC BY-SA 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_060",
    "title": "​黄果树瀑布景观",
    "category": "scenic",
    "city": "安顺",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%20outside%2003.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%20outside%2003.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Huangguoshu%20Waterfall%20outside%2003.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHuangguoshu_Waterfall_outside_03.jpg",
    "author": "晾衣杆",
    "license": "CC BY-SA 4.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_061",
    "title": "Stone steps on Mount Fanjing, in Jiangkou County, Guizhou, C",
    "category": "scenic",
    "city": "铜仁",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20steps%2C%20Mount%20Fanjing%2C%20Picture16.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20steps%2C%20Mount%20Fanjing%2C%20Picture16.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20steps%2C%20Mount%20Fanjing%2C%20Picture16.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AStone_steps%2C_Mount_Fanjing%2C_Picture16.jpg",
    "author": "Huangdan2060",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_062",
    "title": "Jinding or Golden Summit of Mount Fanjing, in Jiangkou Count",
    "category": "scenic",
    "city": "铜仁",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020j.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020j.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jinding%2C%20Mount%20Fanjing%2C%2031%20March%202020j.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AJinding%2C_Mount_Fanjing%2C_31_March_2020j.jpg",
    "author": "Huangdan2060",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_063",
    "title": "Shops on Mount Fanjing, in Jiangkou County, Guizhou, China.",
    "category": "scenic",
    "city": "铜仁",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Shops%2C%20Mount%20Fanjing%2C%2031%20March%202020a.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Shops%2C%20Mount%20Fanjing%2C%2031%20March%202020a.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Shops%2C%20Mount%20Fanjing%2C%2031%20March%202020a.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AShops%2C_Mount_Fanjing%2C_31_March_2020a.jpg",
    "author": "Huangdan2060",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_064",
    "title": "Mount Fanjing in Jiangkou County, Guizhou, China.",
    "category": "scenic",
    "city": "铜仁",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Mount%20Fanjing%2C%2031%20March%202020c.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Mount%20Fanjing%2C%2031%20March%202020c.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Mount%20Fanjing%2C%2031%20March%202020c.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AMount_Fanjing%2C_31_March_2020c.jpg",
    "author": "Huangdan2060",
    "license": "CC BY 3.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_065",
    "title": "Jiaxiu Pavilion in Guiyang. Taken on 10 June 2018.",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2C%20Guiyang.jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2C%20Guiyang.jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2C%20Guiyang.jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AJiaxiu_Pavilion%2C_Guiyang.jpg",
    "author": "xiquinhosilva",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_066",
    "title": "Jiaxiu Pavilion is a building on a giant stone on the Nanmin",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2085234-Guiyang%20(48696602498).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2085234-Guiyang%20(48696602498).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2085234-Guiyang%20(48696602498).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AJiaxiu_Pavilion_85234-Guiyang_(48696602498).jpg",
    "author": "xiquinhosilva",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  },
  {
    "id": "gz_067",
    "title": "Jiaxiu Pavilion is a building on a giant stone on the Nanmin",
    "category": "city",
    "city": "贵阳",
    "lat": null,
    "lng": null,
    "thumbUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2085338-Guiyang%20(48696604988).jpg?width=320",
    "cardUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2085338-Guiyang%20(48696604988).jpg?width=720",
    "detailUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiu%20Pavilion%2085338-Guiyang%20(48696604988).jpg?width=1440",
    "source": "wikimedia-commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AJiaxiu_Pavilion_85338-Guiyang_(48696604988).jpg",
    "author": "xiquinhosilva",
    "license": "CC BY 2.0",
    "verifiedRealPhoto": true,
    "aiGenerated": false
  }
];

  const FALLBACK_ART = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" width="720" height="900" viewBox="0 0 720 900">' +
    '<rect width="720" height="900" fill="#E7E2D2"/>' +
    '<path d="M0 700 Q180 520 340 680 Q520 480 720 660 V900 H0 Z" fill="#C9CDBB" opacity=".7"/>' +
    '<path d="M0 780 Q200 640 400 760 Q560 660 720 770 V900 H0 Z" fill="#A9B3A0" opacity=".6"/>' +
    '<text x="36" y="860" fill="#6E7A68" font-size="26" font-family="serif">GUIZHOU · PHOTO</text></svg>');

  function url(id, size) {
    const photo = PHOTOS.find(p => p.id === id);
    if (!photo) return FALLBACK_ART;
    return photo[(size || "card") + "Url"] || photo.cardUrl;
  }

  function pick(category, index) {
    const list = PHOTOS.filter(p => !category || p.category === category);
    return list[(index || 0) % Math.max(1, list.length)] || null;
  }

  /* 执行文档 §36：真实图片加载失败 → 统一低饱和 Placeholder，禁止 AI 补图 */
  document.addEventListener("error", function (event) {
    const el = event.target;
    if (el && el.tagName === "IMG" && !el.dataset.gxPhotoFallback) {
      el.dataset.gxPhotoFallback = "1";
      el.src = FALLBACK_ART;
    }
  }, true);

  window.GuikePhotos = { photos: PHOTOS, fallback: FALLBACK_ART, url, pick };
})();
